name: Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0 # https://typicode.github.io/husky/how-to.html#ci-server-and-docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: write
  deployments: write
  pull-requests: write
  id-token: write

jobs:
  Process:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        id: release-please
        with:
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}
          relase-type: node
      - name: Print Release Data
        run: |
          echo 'Release Data:'

          echo '''
            ${{ toJSON(steps.release-please.outputs) }}
          '''

  Deploy:
    needs: Process
    runs-on: ubuntu-latest
    if: ${{ needs.Process.outputs.releases_created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: 18.x

      - name: Install dependencies
        run: pnpm i

      - name: Check Formatting
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:cov

      - name: Build
        run: pnpm build

      - name: Test Packaging
        run: pnpm test:package

      - name: Release
        run: |
          pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
